import React from 'react'
import Layout from "../src/layout/Layout";
import Link from "next/link";
import PageBanner from "../src/components/PageBanner";
const Privacy = () => {
    return (
        <Layout footer={3}>
            <PageBanner pageName={"Privacy Policy"} />
            <section>
                <div className='container' style={{marginTop:'100px'}}>
                    <h3>PRIVACY POLICY</h3>
                    <h4>Last updated: November 27, 2023</h4>
                    <h4>This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</h4>

                    <h2>INTERPRETATION AND DEFINITIONS</h2>
                    <h4>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</h4>
                    <h2>DEFINITIONS</h2>
                    <h4>For the purposes of this Privacy Policy:</h4>
                    <ul>
                        <li style={{ listStyle: 'block' }}><b>Account</b> means a unique account created for You to access our Service or parts of our Service.</li>
                        <li style={{ listStyle: 'block' }}><b>Affiliate</b> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for the election of directors or other managing authority.</li>
                        <li style={{ listStyle: 'block' }}><b>Company </b>(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Hi-Fi.</li>
                        <li style={{ listStyle: 'block' }}><b>Cookies</b> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                        <li style={{ listStyle: 'block' }}><b>Country</b> refers to: Tamil Nadu, India.</li>
                        <li style={{ listStyle: 'block' }}><b>Device</b> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
                        <li style={{ listStyle: 'block' }}><b>Personal Data</b> is any information that relates to an identified or identifiable individual.</li>
                        <li style={{ listStyle: 'block' }}><b>Service</b> refers to the Website.</li>
                        <li style={{ listStyle: 'block' }}><b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</li>
                        <li style={{ listStyle: 'block' }}><b>Third-party Social Media Service</b> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
                        <li style={{ listStyle: 'block' }}><b>Usage Data </b>refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                        <li style={{ listStyle: 'block' }}><b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>

                    </ul>

                    <h4>COLLECTING AND USING YOUR PERSONAL DATA</h4>
                    <h4>Types of Data Collected</h4>
                    <h4>Personal Data</h4>
                    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                    <ul>

                        <li style={{ listStyle: 'disc' }}><b>Email address</b>  </li>
                        <li style={{ listStyle: 'disc' }}><b>Phone number</b>  </li>
                        <li style={{ listStyle: 'disc' }}><b>Address, State, Province, ZIP/Postal code, City</b>  </li>
                        <li style={{ listStyle: 'disc' }}><b>Usage Data</b>  </li>
                    </ul>
                    <h4>USAGE DATA</h4>
                    <h5>Usage Data is collected automatically when using the Service.</h5>
                    <h6>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</h6>
                    <h4>TRACKING TECHNOLOGIES AND COOKIES</h4>
                    <h6>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</h6>
                    <ul>
                        <li style={{ listStyle: 'disc' }}><b>Cookies or Browser Cookies:</b>  A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies. </li>

                        <li style={{ listStyle: 'disc' }}><b>Web Beacons:</b>  Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).  </li>
                        <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.

                            We use both Session and Persistent Cookies for the purposes set out below:</p>
                        <li style={{ listStyle: 'disc' }}><b>Necessary / Essential Cookies</b>  </li>
                        <li ><b>Administered by:</b> Us  </li>
                        <li ><b>Purpose: </b> These Cookies identify if users have accepted the use of cookies on the Website. </li>
                        <li style={{ listStyle: 'disc' }}><b>Functionality Cookies</b>  </li>
                        <li ><b>Type:</b>  Persistent Cookies </li>
                        <li ><b>Administered by:</b> Us  </li>
                        <li ><b>Purpose:</b>  These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website. </li>
                        <p>For more information about the cookies we use and your choices regarding cookies, please visit our Privacy Policy.</p>
                    </ul>
<h4>USE OF YOUR PERSONAL DATA</h4>
<h5>The Company may use Personal Data for the following purposes:</h5>
<ul>
<li style={{ listStyle: 'block' }}><b>To provide and maintain our Service, including to monitor the usage of our Service.</b></li>
<li style={{ listStyle: 'block' }}><b>To manage Your Account:</b> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
<li style={{ listStyle: 'block' }}><b>For the performance of a contract:</b> the development, compliance, and undertaking of the purchase contract for the products, items, or services You have purchased or of any other contract with Us through the Service.</li>
<li style={{ listStyle: 'block' }}><b>To contact You:</b> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
<li style={{ listStyle: 'block' }}><b>To provide You with news, special offers and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.`We may share Your personal information in the following situations:</b></li>
<li style={{ listStyle: 'block' }}><b>To manage Your requests:</b> To attend and manage Your requests to Us.</li>
<li style={{ listStyle: 'block' }}><b>For business transfers:</b> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or a similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
<li style={{ listStyle: 'block' }}><b>For other purposes:</b> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service, products, services, marketing, and your experience.</li>
</ul>

<h5>We may share Your personal information in the following situations:</h5>
<li style={{ listStyle: 'block' }}><b>With Service Providers:</b> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
<li style={{ listStyle: 'block' }}><b>For business transfers:</b> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
<li style={{ listStyle: 'block' }}><b>With Affiliates: </b>We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners, or other companies that We control or that are under common control with Us.</li>
<li style={{ listStyle: 'block' }}><b>With business partners:</b> We may share Your information with Our business partners to offer You certain products, services, or promotions.</li>
<li style={{ listStyle: 'block' }}><b>With other users:</b> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures, and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
<h4>RETENTION OF YOUR PERSONAL DATA</h4>
<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.

The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
               <h4>TRANSFER OF YOUR PERSONAL DATA</h4>
               <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
               <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
               <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy, and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place, including the security of Your data and other personal information.</p>
               
               <h4>DELETE YOUR PERSONAL DATA</h4>
               <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
               <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
               <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
                <h4>CHANGES TO THIS PRIVACY POLICY</h4>
                <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
                <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                
                </div>
            </section>
        </Layout>
    );
};
export default Privacy;